mapping_places_profile5 = {
    'Best Kebab': 'Fast Food',
    'Between The Bridges': 'BarPub',
    'Botanist On The Green': 'BarPub',
    'BreadBread': 'Cafe',
    'Bubba Oasis': 'Restaurant',
    'Cafe Sol Clapham': 'Cafe',
    'Cafe+co At 320093': 'Cafe',
    'Candy Stop Ma': 'Supermarket',
    'Co-op': 'Supermarket',
    'Curve Coffee Roast': 'Cafe',
    'Daily Roast': 'Restaurant',
    'FCB Coffee': 'Cafe',
    'Free Soul': 'Supermarket',
    'Gails - Putney': 'Cafe',
    'Gorringe Park': 'BarPub',
    'Gura Gura': 'Restaurant',
    'Harvey?S Bakeh': 'Cafe',
    'Hcp Gelati Ltd': 'Cafe',
    'Kaffee': "Cafe",
    'Kanpai London Ltd.': 'BarPub',
    'Left Handed Giant': 'BarPub',
    'Leon': "Fast Food",
    'M&S': "Supermarket",
    'Mannings Seafood': "Restaurant",
    'Mokoko': "Cafe",
    'Mud Dock': "Cafe",
    'Narrow Kitchen': "Cafe",
    'Needle Vinyl Bar 33rpm': 'BarPub',
    'Olimpia Bakery': "Cafe",
    'Piptree': "Cafe",
    'Pizza Express': "Fast Food",
    'Porterhouse': "Restaurant",
    'Prospect Of Whitby': "Restaurant",
    'Queen Adelaide': 'BarPub',
    'Restaurant Oslo': "Restaurant",
    'Sainsburyâ€™s': "Supermarket",
    "Sambrook's Brewery": 'BarPub',
    'Social Brew London': 'BarPub',
    'Southwark Brew': 'BarPub',
    'Sumupfiligrill': "Restaurant",
    'Tesco': "Supermarket",
    'The Angel And Crown': "BarPub",
    'The Arch House': 'BarPub',
    'The Barrel Project': 'BarPub',
    'The Battersea General': "Supermarket",
    'The Bedford': 'BarPub',
    'The Blues Kitchen': 'BarPub',
    'The Catherine Wheel': 'BarPub',
    'The Kings Tun': 'BarPub',
    'The Lexington': 'BarPub',
    'The Lighthouse         ': 'BarPub',
    'The Phoenix ': 'BarPub',
    'The White Horse': 'BarPub',
    'The Woodman': 'BarPub',
    'Toad Bakery': "Cafe",
    'WHSmith': "Supermarket",
    'Waitrose & Partners': "Supermarket",
    'Wasabi Putney': "Restaurant",
    'Xylo Brewing L': 'BarPub',
    'Youngs': "Restaurant"
}

mapping_places_profile4 = {
    'Amazon Fresh': "Supermarket",
    'Antiparos Vibes': "Restaurant",
    'Artopiotis O Takis': "Supermarket",
    'Blender': "Restaurant",
    'Blue Star Ferries ': "Restaurant",
    'Fotiou Konstantino': "Restaurant",
    'Nefeli Ae': "Restaurant",
    'Sklavenitis_koukaki': "Supermarket",
    'Tserki': "Supermarket",
    'Waitrose & Partners': "Supermarket"
}

mapping_places_profile2 = {
    '28302461 Dub Food Vill': "Restaurant",
    'Another Heart To Feed': "Restaurant",
    'Antonietta Antica Trat': "Restaurant",
    'Backwerk Salzburgmirab': "Cafe",
    'Bread Meats Bread': "Cafe",
    'Brezelkönig': "Cafe",
    'Buffet Pisa': "Restaurant",
    'Caffe Teatro Niccolini': "Cafe",
    'Camillo': "Restaurant",
    'Deliveroo': "Restaurant",
    'Eredi Mosca': "Restaurant",
    "Feltrinelli Cafe' Edit": "Cafe",
    'Gala Dorset St': "Cafe",
    'Hard Rock Cafe': "Restaurant",
    'Hard Rock Cafe Vienna': "Restaurant",
    'Knight?s Bbq L': "Restaurant",
    'Krispy Kreme': "Cafe",
    "L'Etoile Salon de Tea": "Cafe",
    'Los Andes Srl': "Restaurant",
    'M&B Online': "BarPub",
    'Manner Popup': "Fast Food",
    'McDonald’s': "Fast Food",
    'Mei Mei Borough': "Restaurant",
    'Mezza Me': "Restaurant",
    'Mnk Chit N Chat': "Restaurant",
    'Ms Vindobona - Roman L': "Restaurant",
    'Oscars Bar ': "BarPub",
    'Pergola Brixton': "BarPub",
    'Pink Restaurant': "Restaurant",
    'Pizza In Trevi Srl': "Restaurant",
    'Produco Srl': "Supermarket",
    'Refreshment System': "Supermarket",
    'Rid 2004 Srls': "Restaurant",
    'Ristorante Il Toscano': "Restaurant",
    'Ristoro Piccadilly': "Restaurant",
    'Rojalpark Express': "Supermarket",
    'Sainsbury’s': "Restaurant",
    "Salvi's": "Restaurant",
    'Spar': "Restaurant",
    'Starbucks': "Cafe",
    'The Gelatist': "Cafe",
    'The Grocery': "Supermarket",
    'The Lochy': "Restaurant",
    'The Nook': "Restaurant",
    'Tim Hortons': "Cafe",
    'Tuchlaubeneis': "Cafe",
    'WHSmith': "Supermarket",
    'Wing On Express': "Restaurant"
}

mapping_places_profile7 = {
    'ALDI': "Supermarket",
    'Blank Street': "Cafe",
    'Chilli Chilli': "Restaurant",
    'Climpson & Sons': "Cafe",
    'Co-op': "Supermarket",
    'Denbies Wine Estate': "BarPub",
    'Eggslut Stratford': "Restaurant",
    'Hermanos Colombian': "Cafe",
    'Jumbi': "Restaurant",
    'Ls Nourished Communit': "Supermarket",
    'M&S Simply Food': "Supermarket",
    'Mali Vegan': "Restaurant",
    'Mercato Metropolitano': "Restaurant",
    'Peninsula Restaurant': "Restaurant",
    "Roni's Bakery": "Cafe",
    'Rudies Dub Pan Boxp': "Restaurant",
    "Sainsbury's": "Supermarket",
    'Tesco': "Supermarket",
    'The Queens Arms': "BarPub",
    'Tortilla': "Restaurant",
    "Yeye's Noodle+dumplin": "Restaurant",
    "Yeye's Noodle+dumpling": "Restaurant"
}

mapping_places_profile1 ={
    'Almara Beach': "Restaurant",
    'Central Newsagents': "Supermarket",
    'Deliveroo': "Restaurant",
    'Flight Club': "BarPub",
    'Gecko Coffeehouse': "Cafe",
    'Gordon Ramsay Restaura': "Restaurant",
    'Intrepid Baker': "Cafe",
    'Just Eat': "Restaurant",
    'Kinkally': "Restaurant",
    'Leon': "Fast Food",
    'Mare Street Market': "Restaurant",
    'Marks & Spencer': "Restaurant",
    "Nt's Loft": "BarPub",
    'One Circle Cc': "BarPub",
    'Payless Food & Wine': "Supermarket",
    'Restaurant Associates': "Restaurant",
    "Sainsbury's": "Supermarket",
    'Simmons Bar': "BarPub",
    'Square Pub': "BarPub",
    'Tesco': "Supermarket",
    'The Captains Md': "Restaurant",
    'Tufnell Park Food Wine': "BarPub",
    'Tufnell Park Kebab & F': "Fast Food",
    'Tufnell Park Kebab & Fish': "Fast Food",
    'Uber Eats': "Restaurant",
    'WHSmith': "Supermarket",
    'Wondertree': "Restaurant",
    'Zapp': "Supermarket",
}

mapping_places_profile3 = {
    'All That Falafel And C': "Fast Food",
    'Aromi Cafe': "Cafe",
    'Aruba Restaurant & Bar': "Restaurant",
    'Aux Merveilleux De Fred': "Restaurant",
    'Beirut 24 LTD': "Restaurant",
    'Blank Street': "Cafe",
    'Boom Battle Bar': "BarPub",
    'Co-op': "Supermarket",
    'Deliveroo': "Restaurant",
    'Fam Bar': "BarPub",
    'Food On The Move Cater': "Fast Food",
    'Grind': "Supermarket",
    'Hackney Carria': "BarPub",
    'Jshealth Vita': "Supermarket",
    'La Dolce Vita': "Cafe",
    'Leon': "Fast Food",
    'London Grind': "Cafe",
    'London Nootropics': "Supermarket",
    'Los Mochis London': "Restaurant",
    'Louche Soho': "BarPub",
    'Lsp Mallow London': "Restaurant",
    'M&B Online': "BarPub",
    'M&S': "Supermarket",
    'Milk Beach': "Restaurant",
    'Mol London Nootropics': "Supermarket",
    'Pret': "Fast Food",
    'Restaurant Oslo': "Restaurant",
    'Roasting Plant Coffee': "Cafe",
    'Sainsbury’s': "Supermarket",
    'Serpentine Bar & Kitchen': "BarPub",
    'Shake Shack': "Fast Food",
    'Simmons Bar': "BarPub",
    'Tesco': "Supermarket",
    'The Black Horse': "BarPub",
    'The Blues Kitchen': "BarPub",
    'The Lexington': "BarPub",
    'The Little Scarlet Doo': "BarPub",
    'The Noisy Lobster': "Restaurant",
    'The Shoap': "Restaurant",
    'The Sun': "BarPub",
    'Uber Eats': "Restaurant",
    'Urban Baristas': "Cafe",
    'Waitrose & Partners': "Supermarket",
    'White Mulberries': "Cafe",
    'Zoom by Ocado': "Supermarket",
}

mapping_places_profile9 = {
    'All Bar One': "BarPub",
    'Bar- Festival': "BarPub",
    'Black Sheep Coffee': "Cafe",
    'Cafe Sol Clapham': "BarPub",
    'Cittie of Yorke': "BarPub",
    'Clapham Food & Wine': "Restaurant",
    "Dania's Cafe And Bistr": "Cafe",
    'Gather & Gather': "Restaurant",
    'Hannah Battersea': "BarPub",
    'Honest Burgers': "Fast Food",
    'Iceland': "Supermarket",
    'K S Food & Wine': "Supermarket",
    'Lockhouse': "BarPub",
    'Londis': "Supermarket",
    'Longboys': "Cafe",
    'Mc And Sons Vauxhall': "BarPub",
    'McDonald’s': "Fast Food",
    'Nardulli Luxury Ge': "Cafe",
    'Nisa Local': "Supermarket",
    'Oval Event Catering': "Restaurant",
    'Portobello Pub Compa 1': "BarPub",
    'Rufies': "Restaurant",
    'Sainsbury’s': "Supermarket",
    "Sambrook's Brewery": "BarPub",
    'Sumup Kia Oval': "Restaurant",
    'The Alexandra': "BarPub",
    'The Falcon': "BarPub",
    'The Landor': "BarPub",
    'The Railway': "BarPub",
    'Vaulty Towers': "BarPub",
    'Windmill Clapham': "BarPub",
}

mapping_places_profile12 = {
    'M&S': "Supermarket",
    'Morrisons': "Supermarket",
    'Pizza Station': "Fast Food",
    'Sainsbury’s': "Supermarket"
}

mapping_places_profile6 = {
    'ALDI': "Supermarket",
    'B&m 672 Plymouth': "Supermarket",
    'Caffè Nero': "Cafe",
    'Co-op': "Supermarket",
    'Costa Coffee': "Cafe",
    'Greggs': "Cafe",
    'Jacka Bakery': "Cafe",
    'Lidl': "Supermarket",
    'Lindt': "Supermarket",
    "Malcolm Barnecutt's Bakeries": "Cafe",
    'Marks & Spencer': "Supermarket",
    "McDonald's": "Fast Food",
    'One Stop': "Supermarket",
    'Premier Grocery Stores': "Supermarket",
    'Pret A Manger': "Cafe",
    "Sainsbury's": "Supermarket",
    'Tesco': "Supermarket",
    'Too Good To Go': "Cafe",
    'Uber Eats': "Restaurant",
}

mapping_places_profile11 = {
    'Birdies Bar': "BarPub",
    'Bonga': "Restaurant",
    'BrewDog': "BarPub",
    'Camden Beer Hall': "BarPub",
    'Co-op': "Supermarket",
    'Colicci': "Cafe",
    "Corrochio's Dalston": "Restaurant",
    'Costa Coffee': "Cafe",
    'Cronyx Corner': "Supermarket",
    'D4100 Tele Hill': "Restaurant",
    'Deliveroo': "Restaurant",
    'East of England Co-op': "Supermarket",
    'Electric Coffee Co': "Supermarket",
    'Greggs': "Cafe",
    'Holland & Barrett': "Supermarket",
    'Laroash': "Fast Food",
    'Lidl': "Supermarket",
    'Live Nation Bar': "BarPub",
    'Luna Springs': "BarPub",
    'M&B Online': "BarPub",
    'M&S': "Supermarket",
    'MOC Kitchen': "Restaurant",
    'Manzil S': "Restaurant",
    'McDonald’s': "Fast Food",
    'Morrisons': "Supermarket",
    'Mother Clucker Burger': "Restaurant",
    'Pizza Union': "Restaurant",
    'Poundland': "Supermarket",
    'Red Box': "Cafe",
    'Red Cork': "BarPub",
    'Revival Cafe': "Cafe",
    'Sainsbury’s': "Supermarket",
    'Sams': "Fast Food",
    'Smashbite': "Fast Food",
    'Tesco': "Supermarket",
    'The Earl of Camden': "BarPub",
    'The Glove That Fits': "BarPub",
    'The Munch': "Restaurant",
    'Toca Social Birmingham': "BarPub",
    'Uber Eats': "Restaurant",
    'Umana Yana': "Restaurant",
    'West Kebab & Fish Bar': "BarPub",
    'Wetherspoon': "BarPub"
}

mapping_places_profile10 = {
    'Bear Hockley': "Cafe",
    'Beeston Halal Food Store': "Supermarket",
    'Caffè Nero': "Cafe",
    'Kokoro': "Restaurant",
    "McDonald's": "Fast Food",
    'Portland Coffee Co.': "Cafe",
    'Poundland': "Supermarket",
    'Robert Smith & Son': "Supermarket",
    'Tesco': "Supermarket",
    'Too Good To Go': "Cafe"
}
